INSERT INTO course_syllabus (course_id, title, topics, sort_order) VALUES
(2, 'Figma საფუძვლები', ARRAY['Interface და Tools', 'Frames და Components', 'Auto Layout', 'Variants'], 1),
(2, 'User Research', ARRAY['Interview techniques', 'User Personas', 'Journey Mapping'], 2),
(2, 'Wireframing', ARRAY['Low-fidelity wireframes', 'Information Architecture', 'User Flows'], 3),
(2, 'Visual Design', ARRAY['Typography', 'Color Theory', 'Grid Systems'], 4),
(2, 'Design Systems', ARRAY['Component Library', 'Design Tokens', 'Developer Handoff'], 5),
(3, 'Meta ეკოსისტემა', ARRAY['Business Suite', 'Ads Manager', 'Page setup'], 1),
(3, 'კამპანიის სტრუქტურა', ARRAY['Campaign objectives', 'Ad Sets', 'Budget'], 2),
(3, 'ტარგეტირება', ARRAY['Core audiences', 'Custom audiences', 'Lookalike audiences'], 3),
(3, 'ანალიტიკა', ARRAY['Pixel setup', 'Conversion tracking', 'A/B testing'], 4),
(4, 'SEO საფუძვლები', ARRAY['როგორ მუშაობს Google', 'Crawling და Indexing', 'Ranking ფაქტორები'], 1),
(4, 'Keyword Research', ARRAY['Keyword tools', 'Search intent', 'Long-tail keywords'], 2),
(4, 'On-page SEO', ARRAY['Title tags', 'Meta descriptions', 'Internal linking'], 3),
(4, 'Content Strategy', ARRAY['Content calendar', 'Blog writing', 'Distribution channels'], 4),
(5, 'AI კოდირების შესავალი', ARRAY['რა არის Vibe Coding', 'AI ინსტრუმენტები', 'Cursor IDE setup'], 1),
(5, 'Prompt Engineering', ARRAY['ეფექტური პრომპტები', 'Claude vs ChatGPT', 'Iterative development'], 2),
(5, 'ვებ აპლიკაცია AI-ით', ARRAY['React + Tailwind', 'Backend გენერაცია', 'Database დიზაინი'], 3),
(5, 'მობილური აპლიკაცია', ARRAY['React Native AI-ით', 'UI კომპონენტები', 'გამოქვეყნება'], 4),
(6, 'Python საფუძვლები', ARRAY['Variables, Functions', 'Lists, Dicts, Loops', 'Jupyter Notebook'], 1),
(6, 'Pandas და Data Wrangling', ARRAY['DataFrame ოპერაციები', 'Filtering, Grouping', 'Data Cleaning'], 2),
(6, 'SQL', ARRAY['SELECT, WHERE, JOIN', 'GROUP BY, HAVING', 'PostgreSQL პრაქტიკა'], 3),
(6, 'ვიზუალიზაცია', ARRAY['Matplotlib', 'Seaborn', 'Dashboard შექმნა'], 4),
(7, 'კიბერუსაფრთხოების საფუძვლები', ARRAY['CIA Triad', 'TCP/IP, DNS', 'Firewall და VPN'], 1),
(7, 'ეთიკური ჰაკინგი', ARRAY['Kali Linux', 'Reconnaissance', 'Nmap Scanning'], 2),
(7, 'Web Security', ARRAY['OWASP Top 10', 'SQL Injection', 'XSS და CSRF'], 3),
(7, 'Incident Response', ARRAY['SIEM systems', 'Log Analysis', 'Digital Forensics'], 4),
(8, 'PM შესავალი', ARRAY['PM-ის როლი', 'Product Discovery', 'Market Research'], 1),
(8, 'Product Strategy', ARRAY['Vision და Mission', 'Roadmap', 'Prioritization'], 2),
(8, 'Agile და Scrum', ARRAY['Sprint Planning', 'Daily Standups', 'Jira/Linear'], 3),
(8, 'ანალიტიკა', ARRAY['Product Metrics', 'A/B Testing', 'Data-Driven Decisions'], 4),
(9, 'გაყიდვების საფუძვლები', ARRAY['Sales Psychology', 'B2B vs B2C', 'Sales Funnel'], 1),
(9, 'კომუნიკაცია', ARRAY['Cold Calling', 'Email Outreach', 'Social Selling'], 2),
(9, 'მოლაპარაკებები', ARRAY['BATNA და ZOPA', 'Closing ტექნიკები', 'როლური თამაშები'], 3),
(9, 'CRM და ანალიტიკა', ARRAY['HubSpot/Pipedrive', 'Pipeline Management', 'Forecasting'], 4);

INSERT INTO course_faq (course_id, question, answer, sort_order) VALUES
(2, 'დიზაინის გამოცდილება სჭირდება?', 'არა, კურსი ნულიდან იწყება.', 1),
(2, 'Figma ფასიანია?', 'Figma-ს უფასო ვერსია საკმარისია.', 2),
(3, 'მარკეტინგის გამოცდილება სჭირდება?', 'არა, ნულიდან ვისწავლით.', 1),
(3, 'რეკლამის ბიუჯეტი მჭირდება?', 'მინიმალური ბიუჯეტი რეკომენდებულია.', 2),
(4, 'ვებსაიტი უნდა მქონდეს?', 'არა, სადემონსტრაციო საიტებზე ვიმუშავებთ.', 1),
(4, 'რამდენ ხანში ჩანს შედეგი?', 'SEO 2-3 თვეში იწყებს შედეგების ჩვენებას.', 2),
(5, 'პროგრამირების ცოდნა სჭირდება?', 'არა, AI-ით ვქმნით კოდის ცოდნის გარეშე.', 1),
(5, 'რეალურ აპს შევქმნი?', 'დიახ, მინიმუმ 2 მზა აპლიკაცია.', 2),
(6, 'Python-ის ცოდნა სჭირდება?', 'არა, ნულიდან ვისწავლით.', 1),
(6, 'რა კომპიუტერი მჭირდება?', 'ნებისმიერი, Google Colab-ში ვმუშაობთ.', 2),
(7, 'პროგრამირების ცოდნა სჭირდება?', 'Linux command line საბაზისო ცოდნა სასურველია.', 1),
(7, 'ლეგალურია ეთიკური ჰაკინგი?', 'დიახ, ავტორიზებულ ლაბ გარემოში ვმუშაობთ.', 2),
(8, 'ტექნიკური ცოდნა სჭირდება?', 'არა, PM-ს ტექნიკური ცოდნა სავალდებულო არ არის.', 1),
(8, 'პორტფოლიოს გამომივა?', 'დიახ, PRD, Roadmap და Case Study.', 2),
(9, 'გაყიდვების გამოცდილება სჭირდება?', 'არა, ნულიდან ვისწავლით.', 1),
(9, 'B2B თუ B2C ვისწავლი?', 'ორივეს, აქცენტი B2B-ზეა.', 2);
